package com.adempolat.tvlivestreamapp

data class Channel(val name: String, val url: String)

val channelList = listOf(
    Channel("TRT1", "https://tv-trt1-dai.medya.trt.com.tr/master.m3u8"),
    Channel("Kanal d", "https://demiroren-live.daioncdn.net/kanald/kanald.m3u8"),
    Channel("ATV", "https://canlitvulusal.xyz/live/atv/index.m3u8"),
    Channel("Show TV", "https://ciner-live.daioncdn.net/showtv/showtv.m3u8"),
    Channel("Star TV", "https://dogus-live.daioncdn.net/startv/startv.m3u8"),
    Channel("Kanal 7", "https://kanal7-live.daioncdn.net/kanal7/kanal7.m3u8"),
    Channel("NOW TV", "https://nowtv.blutv.com/blutv_nowtv/live.m3u8"),
    Channel("TV8", "https://tv8-live.daioncdn.net/tv8/tv8.m3u8"),
    Channel("TV8 Buçuk", "https://tv8-live.daioncdn.net/tv8bucuk/tv8bucuk.m3u8"),
    Channel("CNN Türk", "https://ythls.armelin.one/video/X_EWYemclKA.m3u8"),
    Channel("NTV", "https://dogus-live.daioncdn.net/ntv/ntv.m3u8"),
    Channel("A Haber", "https://raw.githubusercontent.com/rideordie16/YouTube/main/haber/ahaber.m3u8"),
    Channel("TRT Haber", "https://tv-trthaber.medya.trt.com.tr/master.m3u8"),
    Channel("Habertürk", "https://ciner-live.daioncdn.net/haberturktv/haberturktv.m3u8"),
    Channel("Haber Global", "https://haberglobal.blutv.com/blutv_haberglobal2/live.m3u8"),
    Channel("TRT Spor", "https://tv-trtspor1.medya.trt.com.tr/master.m3u8"),
    Channel("Bein Spor", "https://ythls.armelin.one/channel/UCPe9vNjHF1kEExT5kHwc7aw.m3u8"),
    Channel("A Spor", "https://new.cache-stream.workers.dev/stream/UCJElRTCNEmLemgirqvsW63Q/live.m3u8"),
    Channel("FB TV", "https://1hskrdto.rocketcdn.com/fenerbahcetv.smil/playlist.m3u8"),
    Channel("GS TV", "https://owifavo5.rocketcdn.com/gstv/gstv.smil/master.m3u8"),
    Channel("TRT Spor Yıldız", "https://tv-trtspor2.medya.trt.com.tr/master.m3u8"),
    Channel("360", "https://turkmedya-live.ercdn.net/tv360/tv360.m3u8"),
    Channel("Teve 2", "https://live.duhnet.tv/S2/HLS_LIVE/teve2np/playlist.m3u8"),
    Channel("A2", "https://ythls.armelin.one/channel/UCHqu50_C2U2h_rpzhygs4aA.m3u8"),
    Channel("TRT Belgesel", "https://tv-trtbelgesel-dai.medya.trt.com.tr/master.m3u8"),
    Channel("TGRT Belgesel", "https://b01c02nl.mediatriple.net/videoonlylive/mtsxxkzwwuqtglive/broadcast_5fe462afc6a0e.smil/playlist.m3u8"),
    Channel("TRT Çocuk", "https://tv-trtcocuk.medya.trt.com.tr/master.m3u8"),
    Channel("TRT Müzik", "https://tv-trtmuzik.medya.trt.com.tr/master.m3u8"),
    Channel("Kral Pop", "https://dogus-live.daioncdn.net/kralpoptv/kralpoptv.m3u8"),
    Channel("Dream Türk", "https://live.duhnet.tv/S2/HLS_LIVE/dreamturknp/playlist.m3u8"),
    Channel("Power Türk", "https://live.artidijitalmedya.com/artidijital_powerturktv/powerturktv/playlist.m3u8"),
    Channel("Number1 Türk", "https://b01c02nl.mediatriple.net/videoonlylive/mtkgeuihrlfwlive/broadcast_5c9e187770143.smil/playlist.m3u8"),
    Channel("Flash TV", "https://flashtv.blutv.com/blutv_flashtv/live.m3u8"),
    Channel("CNBC-E TV", "https://new.cache-stream.workers.dev/channel/UCaO-M1dXacMwtyg0Pvovk4w/live.m3u8"),
    Channel("TBMM TV", "https://meclistv-live.ercdn.net/meclistv/meclistv.m3u8"),
    Channel("TV Net", "https://mn-nl.mncdn.com/tvnet/tvnet/playlist.m3u8"),
    Channel("D Max", "https://dogus-live.daioncdn.net/dmax/dmax.m3u8"),
    Channel("TLC", "https://dogus-live.daioncdn.net/tlc/tlc.m3u8"),
    Channel("Show Max", "https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/tur/shmax.m3u8"),
    Channel("Ekol Tv", "https://helga.iptv2022.com/sh/ekol_tv/index.m3u8"),
    Channel("CNBC News", "https://new.cache-stream.workers.dev/stream/UCvJJ_dzjViJCoLf5uKUTwoA/live.m3u8"),
    Channel("FOX News", "https://fox-foxnewsnow-samsungus.amagi.tv/playlist.m3u8"),
    Channel("TRT World", "https://tv-trtworld.medya.trt.com.tr/master.m3u8"),

    )

